#基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'osyo-manga/vim-vigemo'

[[plugins]]
repo = 'vim-scripts/Perfect-Dark'

[[plugins]]
repo = 'rakr/vim-one'
[[plugins]]
repo ='aereal/vim-colors-japanesque' 


[[plugins]]
repo = 'YorickPeterse/happy_hacking.vim'

[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''


[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
 repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]] 
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo =  'evidens/vim-twig'

[[plugins]]
repo =  'w0ng/vim-hybrid'
