[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/unite-session'

# [[plugins]]
# repo = 'osyo-manga/vim-vigemo'

# [[plugins]]
# repo = 'haya14busa/vim-migemo'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
# repo = 'mo-ta/vim-colors-mota'
repo = 'aereal/vim-colors-japanesque'

[[plugins]]
repo = 'cocopon/iceberg.vim'

# [[plugins]]
# repo = 'fuenor/qfixhowm'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo =  'tacroe/unite-mark'
depends = ['unite']

[[plugins]]
repo =  'Shougo/neomru.vim'
depends = ['unite']

[[plugins]]
repo =  'Shougo/neoyank.vim'
depends = ['unite']

[[plugins]]
# repo = 'kana/vim-submode'
repo = 'mo-ta/vim-submode'

#[[plugins]]
#repo = 'vim-scripts/ruby-matchit'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo =  'easymotion/vim-easymotion'

[[plugins]]
repo = 'Shougo/unite-outline'

# [[plugins]]
# repo =  'thinca/vim-ref'

# [[plugins]]
# repo =   'yuku-t/vim-ref-ri'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo =  'kannokanno/previm'

[[plugins]]
repo = 'plasticboy/vim-markdown'
# repo = 'tpope/vim-markdown'

[[plugins]]
repo =  'tyru/open-browser.vim'

[[plugins]]
repo =  'osyo-manga/vim-over'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
# repo = 'rhysd/accelerated-jk'
repo = 'mo-ta/accelerated-jk'

[[plugins]]
repo = 'sgur/unite-qf'

# [[plugins]]
# repo = 'sjl/gundo.vim'


# [[plugins]]
# repo = 'vim-scripts/DrawIt'

[[plugins]]
repo = 'tpope/vim-surround'

# [[plugins]]
# repo = 'szw/vim-tags'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# [[plugins]]
# repo = 'kana/vim-textobj-user'

# [[plugins]]
# repo = 'kana/vim-textobj-line'

# [[plugins]]
# repo = 'kana/vim-textobj-entire'

# [[plugins]]
# repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'tyru/caw.vim'

# [[plugins]]
# repo = 'tpope/vim-fugitive'
# [[plugins]]
# repo = 'JuliaEditorSupport/julia-vim'
#[[plugins]]
#repo = 'delphinus35/typescript-vim'
#rev  = 'colorize-template-strings'
#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'

#[[plugins]]
#repo = 'elzr/vim-json'
#if   = '''! has('kaoriya')'''

#repo = 'osyo-manga/vim-precious'
#depends = ['context_filetype.vim']
#[[plugins]] 
#repo = 'Shougo/context_filetype.vim'


#[[plugins]]
#repo = 'scrooloose/nerdtree'


#[[plugins]]
#repo = 'delphinus35/typescript-vim'
#rev  = 'colorize-template-strings'
#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'

#[[plugins]]
#repo = 'elzr/vim-json'
#if   = '''! has('kaoriya')'''



#repo = 'osyo-manga/vim-precious'
#depends = ['context_filetype.vim']
#[[plugins]] 
#repo = 'Shougo/context_filetype.vim'


#[[plugins]]
#repo = 'scrooloose/nerdtree'

#[[plugins]]
#repo =  'evidens/vim-twig'

#[[plugins]]
#repo =  'w0ng/vim-hybrid'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
#on_i = 1
# hook_add = 'let g:deoplete#enable_at_startup = 1'

# [[plugins]]
# repo = 'roxma/nvim-yarp'
# on_ft = ['ruby']

# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'
# on_ft = ['ruby']

[[plugins]]
repo = 'mechatroner/rainbow_csv'

# [[plugins]]
# repo = 'Shougo/deoplete-rct'
# on_ft = ['ruby']

# [[plugins]]
# repo = 'fishbullet/deoplete-ruby'
# on_ft = ['ruby']

#[[plugins]]
#repo = 'osyo-manga/vim-monster'
#on_i = 1
#hook_add = aaa
#let g:monster#completion#rcodetools#backend = "async_rct_complete"
#let g:deoplete#sources#omni#input_patterns = {
#  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
#  \}
#aaa




#[[plugins]]
#repo = 'ctrlpvim/ctrlp.vim'
# [[plugins]]
# repo = "airblade/vim-gitgutter"

# [[plugins]]
# repo = "tpope/vim-fugitive"

# [[plugins]]
# repo = "Vim-scripts/Align"


# [[plugins]]
# repo = "aklt/plantuml-syntax"
[[plugins]]
repo = "pepo-le/win-ime-con.nvim"

[[plugins]]
repo = "w0rp/ale"

#undoList表示
[[plugins]]
repo = "mbbill/undotree"

[[plugins]]
repo = "neoclide/coc.nvim"
build = 'coc#util#install()'
hook_add = '''
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
  " Remap for rename current word
  nmap <leader>rn <Plug>(coc-rename)
  " Highlight symbol under cursor on CursorHold
  autocmd CursorHold * silent call CocActionAsync('highlight')
  " Use K for show documentation in preview window
  nnoremap <silent> K :call <SID>show_documentation()<CR>
  function! s:show_documentation()
    if &filetype == 'vim'
      execute 'h '.expand('<cword>')
    else
      call CocAction('doHover')
    endif
  endfunction
'''

#repo = "neoclide/coc-solargraph"
 # [[plugins]]
 # repo = "ueokande/popupdict.vim"

